// SAMPLE dev fixture — the FDI engine overwrites this per-build with real Affinity data.
// Schema: see network-data.json in the engine. window.NETWORK_DATA shape.
window.NETWORK_DATA = {
  "schema_version": 1,
  "generated_at": "2026-07-15T00:00:00.000Z",
  "hub": "Primary",
  "build_status": "ok",
  "summary": {
    "companies_total": 4,
    "companies_with_path": 2,
    "coverage_pct": 50,
    "total_relationships": 181,
    "primary_connectors": [
      "Brian Schechter",
      "Cassie Young",
      "Doug Kessler",
      "Nick Daley",
      "Tobias Citron"
    ]
  },
  "companies": [
    {
      "company": "Datadog",
      "domain": "datadoghq.com",
      "affinity_id": 224026487,
      "affinity_name": "Datadog",
      "status": "resolved",
      "total_paths": 134,
      "shown_paths": 4,
      "best_score": 97,
      "paths": [
        {
          "connector": "Tobias Citron",
          "connector_id": 22505167,
          "connector_email": "tobias@primary.vc",
          "contact_name": "Emilio Escobar",
          "contact_id": 151248152,
          "contact_email": "emilio.escobar@datadoghq.com",
          "contact_title": "Chief Information Security Officer",
          "contact_affiliation": "Datadog",
          "at_target_company": true,
          "seniority": "C-Level",
          "linkedin_url": "https://www.linkedin.com/in/emilioesc/",
          "type": "interaction",
          "has_interaction_data": true,
          "score": 97,
          "linkedin_connected": false,
          "last_contact": "2026-07-09",
          "enrichment_status": "ok"
        },
        {
          "connector": "Nick Daley",
          "connector_id": 243020030,
          "connector_email": "nick@primary.vc",
          "contact_name": "Jack Friedson",
          "contact_id": 257939519,
          "contact_email": "jack.friedson@gmail.com",
          "contact_title": "Angel Investor",
          "contact_affiliation": "Independent",
          "at_target_company": false,
          "seniority": null,
          "linkedin_url": null,
          "type": "interaction",
          "has_interaction_data": true,
          "score": 96,
          "linkedin_connected": false,
          "last_contact": null,
          "enrichment_status": "ok"
        },
        {
          "connector": "Tobias Citron",
          "connector_id": 22505167,
          "connector_email": "tobias@primary.vc",
          "contact_name": "Ignacio De Diego Salto",
          "contact_id": 195159693,
          "contact_email": "ignacio.dediego@cardumencapital.com",
          "contact_title": "Partner",
          "contact_affiliation": "Cardumen Capital",
          "at_target_company": false,
          "seniority": "Partner",
          "linkedin_url": "https://www.linkedin.com/in/idediego/",
          "type": "interaction",
          "has_interaction_data": true,
          "score": 96,
          "linkedin_connected": false,
          "last_contact": "2026-05-01",
          "enrichment_status": "ok"
        },
        {
          "connector": "Brian Schechter",
          "connector_id": 13145313,
          "connector_email": "brian@primary.vc",
          "contact_name": "Dana Reed",
          "contact_id": 999000001,
          "contact_email": "dana.reed@datadoghq.com",
          "contact_title": "Staff Engineer",
          "contact_affiliation": "Datadog",
          "at_target_company": true,
          "seniority": "Senior",
          "linkedin_url": "https://www.linkedin.com/in/danareed/",
          "type": "linkedin",
          "has_interaction_data": false,
          "score": null,
          "linkedin_connected": true,
          "last_contact": null,
          "enrichment_status": "ok"
        }
      ]
    },
    {
      "company": "Ramp",
      "domain": "ramp.com",
      "affinity_id": 330000001,
      "affinity_name": "Ramp",
      "status": "resolved",
      "total_paths": 47,
      "shown_paths": 4,
      "best_score": 88,
      "paths": [
        {
          "connector": "Cassie Young",
          "connector_id": 37522938,
          "connector_email": "cassie@primary.vc",
          "contact_name": "Maya Chen",
          "contact_id": 400001,
          "contact_email": "maya@ramp.com",
          "contact_title": "VP of Finance",
          "contact_affiliation": "Ramp",
          "at_target_company": true,
          "seniority": "VP",
          "linkedin_url": "https://linkedin.com/in/mayachen",
          "type": "interaction",
          "has_interaction_data": true,
          "score": 88,
          "linkedin_connected": false,
          "last_contact": "2026-06-30",
          "enrichment_status": "ok"
        },
        {
          "connector": "Brian Schechter",
          "connector_id": 13145313,
          "connector_email": "brian@primary.vc",
          "contact_name": "Omar Silva",
          "contact_id": 400002,
          "contact_email": "omar@ramp.com",
          "contact_title": "Head of Data",
          "contact_affiliation": "Ramp",
          "at_target_company": true,
          "seniority": "Director",
          "linkedin_url": "https://linkedin.com/in/omarsilva",
          "type": "interaction",
          "has_interaction_data": true,
          "score": 64,
          "linkedin_connected": true,
          "last_contact": "2026-04-10",
          "enrichment_status": "ok"
        },
        {
          "connector": "Cassie Young",
          "connector_id": 37522938,
          "connector_email": "cassie@primary.vc",
          "contact_name": "Priya Nair",
          "contact_id": 400003,
          "contact_email": "priya@venturex.com",
          "contact_title": "Partner",
          "contact_affiliation": "Venture X",
          "at_target_company": false,
          "seniority": "Partner",
          "linkedin_url": "https://linkedin.com/in/priyanair",
          "type": "interaction",
          "has_interaction_data": true,
          "score": 41,
          "linkedin_connected": false,
          "last_contact": "2026-05-15",
          "enrichment_status": "ok"
        },
        {
          "connector": "Doug Kessler",
          "connector_id": 99,
          "connector_email": "doug@primary.vc",
          "contact_name": "Sam Okoye",
          "contact_id": 400004,
          "contact_email": "sam@ramp.com",
          "contact_title": "Senior PM",
          "contact_affiliation": "Ramp",
          "at_target_company": true,
          "seniority": "Senior",
          "linkedin_url": null,
          "type": "linkedin",
          "has_interaction_data": false,
          "score": null,
          "linkedin_connected": true,
          "last_contact": null,
          "enrichment_status": "ok"
        }
      ]
    },
    {
      "company": "Brex",
      "domain": "brex.com",
      "affinity_id": 330000002,
      "affinity_name": "Brex",
      "status": "no_relationships",
      "total_paths": 0,
      "paths": []
    },
    {
      "company": "Northwind AI",
      "domain": "notacompany-xyz.com",
      "status": "not_found",
      "total_paths": 0,
      "paths": []
    }
  ]
};
